Default: &defaults
  database: semeion.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: semeion_test.sqlite3
  <<: *defaults

Staging:
  database: semeion_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: semeion_production.sqlite3
  poolsize: 100
  <<: *defaults
